### ISSUE TITLE
Paragraphs - Dictionary Word Entry migration reporting success but silently failing

### ISSUE THREAD

**Issue by taylor-steve** [MukurtuCMS/Mukurtu-CMS#174]
The Paragraphs - Dictionary Word Entry on the PPWP test migration reports success, but no entities are created and it appears that it does not flag itself as successful for the purposes of the migration. The dictionary word migration fails with:

`Migration mukurtu_cms_v3_dictionary_word did not meet the requirements. Missing migrations mukurtu_cms_v3_paragraphs_dictionary_word_entry. requirements: mukurtu_cms_v3_paragraphs_dictionary_word_entry.`

**Comment by michael-wynne-wsu** [comment]
@nick-deer Absolutely. It's entirely possible this was resolved but not logged. Let me see if I can replicate it first and then I'll get back to you.

**Comment by michael-wynne-wsu** [comment]
@nick-deer Confirming that it seems fine to me.

Can you test one more thing for me? Test migrating a word with MULTIPLE word entries. My test batch only had words with a single paragraph entry and I need to wait for Brian to rebuild my site before testing again.

I did notice two other issues on migration, will tag you in those.

**Comment by nick-deer** [comment]
@michael-wynne-wsu I migrated one dictionary word with 3 word entries. Three of em made it over, but with some quirks: 

- For some recordings, the media player is not showing up. All the media ids are being migrated, however.
- Pronunciation field data is not migrating, hence not showing up.
- Word Origin field is displaying the term's id rather than the term itself. 
- (Sample sentences missing as noted in: https://github.com/MukurtuCMS/Mukurtu-CMS/issues/571)

**Comment by michael-wynne-wsu** [comment]
@nick-deer 

1) Some media players not displaying: Good to know, I didn't spot that on my test but I'll do another pass looking for it.
2) Pronunciation field: Do you want me to create a dedicated issue for that?
3) Word Origin: Shouldn't be migration-related since it's a new field in v4. It's also a text field, not a taxonomy field, so interesting that you're seeing an ID?

**Comment by nick-deer** [comment]
@michael-wynne-wsu regarding the pronunciation field, yes please make an issue for it unless it exists already! And about the word origin field, I see now that there is a mistake in the migration--it needs to be field word type instead! I'll push that change soon

**Comment by michael-wynne-wsu** [comment]
Yep, Part of speech (v3) > word type (v4) is the relevant mapping there!

**Comment by nick-deer** [comment]
@michael-wynne-wsu got word type migrating successfully!

**Comment by michael-wynne-wsu** [comment]
@nick-deer awesome!

Since the other items have their own issues I think this one can be completed.
