### ISSUE TITLE
Browse all updates

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#350]
At /browse.

- [x]  1) Map view is not loading.
- [x]  2) Otherwise MOST things in https://github.com/MukurtuCMS/Mukurtu-CMS/issues/351 should apply here as well.
- [ ] 3) ~~Facet order should be: community > cultural protocols > content type > category > collection (not currently listed) > media type > keywords --digital-heritage should be the same but without content type facet~~ See #628

**Comment by michael-wynne-wsu** [comment]
@pjudge clarified/updates the issue description

**Comment by pjudge** [comment]
@michael-wynne-wsu Apparently changing the order of the facets is a much bigger lift than it should be.  Facets 2.0.7 (which we're locked at because 2.0.9 is for D10+) requires a patch (https://www.drupal.org/project/facets/issues/3251920). 

The patch, however, is added to the Facets Summary submodule inside of the Facets module. We're not using the Facets Summary module. We could be, however I am having a hard time figuring out what it actually provides that the regular facets module does not. Once enabled, it has to be set up and configured correctly, and the views have to be updated to use the Facets Summary block as a datasource. 

I also think some updates to the Mukurtu Browse custom module are required for all this, and it's turning into quite the rabbithole that is probably better suited to a Back End dev.

**Comment by michael-wynne-wsu** [comment]
@pjudge gosh, what a tangle! Yes, we can class this as back-end/to be revisited (@quicksketch is helping us get over to D10 in the coming weeks), so hopefully that helps in the future.

Would you be able to make a dedicated issue for that? And then I think this one can be closed.
