### ISSUE TITLE
Location record

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#90]
In thinking about a location record (similar to a person record), an obvious choice would be to add a location taxonomy field to content types to serve as the connection between content.

What about being able to select a shape on a map and pull all content within that area into the location record? I'd be curious on your thoughts if that's worth exploring. @steve-taylor-wsu @nick-deer

**Comment by kimberlychristen** [comment]
We’ve had this request in the past from users, I think it would be popular, if doable. For many reasons precise locations can’t always be used or documented.--KimOn Aug 22, 2023, at 2:44 PM, Michael Wynne ***@***.***> wrote:﻿
In thinking about a location record (similar to a person record), an obvious choice would be to add a location taxonomy field to content types to serve as the connection between content.
What about being able to select a shape on a map and pull all content within that area into the location record? I'd be curious on your thoughts if that's worth exploring. @steve-taylor-wsu @nick-deer

**Comment by steve-taylor-wsu** [comment]
If we are open to:
* Requiring SOLR
* Making our locations single point or adding a computed "centroid" field to reduce our location field down to a single lat/lng point (we'd have to brainstorm on this one, I think right now each item can have any number of arbitrary shapes)
* Restricting the query shape to a rectangle

We could likely do location based dynamic queries with tools already available to us.

We can definitely talk about how we'd do it otherwise, but that looks to be the only supported (loosely, the modules are still in "alpha", we'll have to test, might not even work) method that currently exists in the Drupal ecosystem.

**Comment by michael-wynne-wsu** [comment]
Thanks @steve-taylor-wsu that makes sense. Given our pre-existing requirements around SOLR, and those other requirements, I don't think we should pursue that for now. Adding a location taxonomy field will probably be sufficient...

@kimberlychristen we do have areas available in mapping, not just points! I was specifically thinking about how to identify which items would be included in a location record. For person records you have to select the person's name(s) - we could do the same for locations, but I wanted to see if we could have a different way to select places.

**Comment by michael-wynne-wsu** [comment]
Updating to a defined request.

Please add a new taxonomy and field for "Location". I am also considering "Place" instead - anyone have preference for one over the other?

- Multi-value
- Add on the fly enabled
- Add to DH items (with other location-type fields)
- Add to base dictionary words (not word entry/paragraphs)

**Comment by nick-deer** [comment]
Alright @michael-wynne-wsu I pushed up a working Location taxonomy and field! Let me know as always if you have any suggestions

**Comment by michael-wynne-wsu** [comment]
@nick-deer it's working as expected, thank you!
